name: www.simonpoolemusic.com
favicon: null
layout_spectrum: 0.3288476658053696
typography_spectrum: 0.19754017237573862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#6c6c6c'
    - '#505050'
    - '#eeeeee'
    - '#cdcdcd'
  brandStrength: 0.4375
  lightness: 0.7002415384631604
  saturation: 0.6354777675587684
  rhythmicContrast: 0.25
purpose: []
